# Generated by Django 3.2 on 2021-04-18 16:18

import colorfield.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Nachname"),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Stundenansatz"
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#1976d2", max_length=18),
                ),
            ],
            options={
                "verbose_name": "Kunde",
                "verbose_name_plural": "Kunden",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Adresse")),
                (
                    "zip_code",
                    models.CharField(max_length=4, verbose_name="Postleitzahl"),
                ),
                ("place", models.CharField(max_length=255, verbose_name="Ort")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primäradresse"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adressen",
            },
        ),
    ]
