# Generated by Django 3.2 on 2021-05-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="sex",
            field=models.CharField(
                choices=[("MALE", "Herr"), ("FEMALE", "Frau")],
                default="MALE",
                max_length=255,
                verbose_name="Geschlecht",
            ),
        ),
    ]
