# Generated by Django 3.2 on 2021-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='route_flat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Wegpauschale'),
        ),
    ]
