# Generated by Django 3.2 on 2021-10-13 20:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start', models.DateTimeField(verbose_name='Startzeit')),
                ('end', models.DateTimeField(null=True, verbose_name='Endzeit')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('route_flat', models.BooleanField(default=True, verbose_name='Wegpauschale')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='customer.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapporte',
            },
        ),
    ]
