# Generated by Django 3.2 on 2021-05-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="route_flat",
            field=models.BooleanField(default=True, verbose_name="Wegpauschale"),
        ),
    ]
