# Generated by Django 3.2 on 2021-10-13 20:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='')),
                ('source_file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('CREATED', 'Erstellt'), ('SENT', 'Versendet'), ('PAYED', 'Bezahlt'), ('ARCHIVED', 'Archiviert')], default='CREATED', max_length=255, verbose_name='Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customer.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
            },
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('CREATED', 'Erstellt'), ('SENT', 'Versendet'), ('PAYED', 'Bezahlt'), ('ARCHIVED', 'Archiviert')], default='CREATED', max_length=255, verbose_name='Status')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyentries', to='invoice.invoice', verbose_name='Rechnung')),
            ],
            options={
                'verbose_name': 'Verlaufeintrag',
                'verbose_name_plural': 'Verlaufeinträge',
            },
        ),
    ]
